apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: maplify-tech

resources:
- namespace.yaml
- web-deployment.yaml
- api-deployment.yaml
- postgres-statefulset.yaml
- minio-deployment.yaml
- ingress.yaml
- configmap.yaml
# - secrets.yaml  # Uncomment after creating from secrets.yaml.example

commonLabels:
  app.kubernetes.io/name: maplify-tech
  app.kubernetes.io/version: "1.0.0"
  app.kubernetes.io/managed-by: kustomize
